# Pull base image.
FROM ubuntu:latest
ARG DEBIAN_FRONTEND=noninteractive

# Install Linux Dependencies.
RUN \
    apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y python3 && \
    apt-get install -y python3-pip && \
    apt-get install -y curl && \
    apt-get install -y sudo && \
    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

# Add files.
ADD src/ .

# Install Python Dependencies.
RUN \
    python3 -m pip install -r requirements.txt


# Install Azure CLI extension.
RUN \
    az extension add --name azure-iot && \
    chmod +x ./entrypoint.sh


ENTRYPOINT ./entrypoint.sh

