version: '3'
services:
  trucks:
    image: "trucks"
    env_file: ./.env
    environment:
      DEVICE_ID: "Truck-000{{.Task.Slot}}"
    deploy:
      replicas: 8

  warehouse:
    image: "warehouse"
    env_file: ./.env
    environment:
      DEVICE_ID: "Warehouse-000{{.Task.Slot}}"
    deploy:
      replicas: 3